config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "location#index"
  resources "location"
  resources "review"
  resources "photo"
  resources "report"
  get "admin", to: "admin#index"
  get "/googleb644d22d0a6d8ad2.html", to: "report#googleb644d22d0a6d8ad2"
  get "/landing", to: "user#landing"
  get "/users/all", to: "user#index"
  get "/collection_api", to: "photo#collection_api"
  get "/geo_json_api", to: "location#geo_json_api"
  get "/my_location_api", to: "location#my_location_api"
  get "/user/show/:id", to: "user#show"
  get "/user/enable_account/:id", to: "user#enable_account"
  get "/user/disabled_account/:id", to: "user#disabled_account"
  get "/user/send_email_verification/:id", to: "user#send_email_verification"
  post "/reset_password", to: "user#reset_password"
  get "/new_password/:id", to: "user#new_password"
  post "/change_password/:id", to: "user#change_password"
  delete "/report_destroy/:id", to: "report#report_destroy"
  get "/user/edit_profile/:id", to: "user#edit_profile_image"
  post "/user/update_profile/:id", to: "user#update_profile_image"
  get "/location/admin/merge", to: "location#merge"
  post "/location/admin/merge", to: "location#merge_back_end"
  namespace :api do
    namespace :v1 do
      resources :sessions
      resources :locations
      resources :photos
      resources :users
      resources :reviews
      resources :reports

      post "/sessions/authenticate", to: "sessions#authenticate"
      post "/sessions/create_user", to: "sessions#create_user"
      post "/sessions/edit_user", to: "sessions#edit_user"
      post "/users/password/reset", to: "users#reset_password"

      get "/locations/find/search", to: "locations#search"

    end
  end
end

app/controllers/api/v1/reviews_controller.rb
class Api::V1::ReviewsController < ApiController
  before_action :is_authencticated, only: [:update, :create]
  before_action :set_review, only: [:update]
  before_action :is_mine, only: [:update]
  before_action :is_verified, only: [:update, :create]

  def update
    if @review.update_attributes(review_params)
      render_reviews
    else
      render json: {errors: @review.errors}
    end
  end

  def create
    @review = Review.create(review_params)
    if @review.save
      render_reviews
    else
      render json: {errors: @review.errors}
    end
  end

  private

    def review_params
      {message: params[:message], score: params[:score], location_id: params[:location_id], user_id: @user.id}
    end

    def render_reviews
      location = Location.find(params[:location_id])
      ph = location.photos.mostViews
      users = User.joins(:photos).where("photos.location_id = #{location.id}").order("photos.views DESC")
      photos = ph.zip(users).map do |p, u|
        { id: p.id, zoom: p.zoom, offsetX: p.offsetX, offsetY: p.offsetY, width: p.width, height: p.height, caption: p.caption, user_id: p.user_id, img_url: p.img_url.url, views: p.views, user_display: u.display, user_profile: u.profile_img.url, user_zoom: u.zoom, user_width: u.width, user_height: u.height, user_offsetX: u.offsetX, user_offsetY: u.offsetY}
      end
      rv_users = User.find_by_sql("SELECT u.* FROM users u JOIN reviews r ON r.user_id = u.id WHERE r.location_id = #{location.id} ORDER BY r.score DESC")
      rv = Review.find_by_sql("SELECT r.* FROM reviews r JOIN users u ON r.user_id = u.id WHERE r.location_id = #{location.id} ORDER BY r.score DESC")
      reviews = rv.zip(rv_users).map do |r, u|
        { id: r.id, score: r.score, message: r.message ,user_id: r.user_id, user_display: u.display, user_profile: u.profile_img.url, user_zoom: u.zoom, user_width: u.width, user_height: u.height, user_offsetX: u.offsetX, user_offsetY: u.offsetY}
      end
      render json:  { location: location, photos: photos, reviews: reviews }
    end

    def set_review
      @review = Review.find(params[:id])
    end

    def is_mine
      if @user.id != @review.user_id
        head(:unauthorized)
      end
    end

    def is_authencticated
      @user = nil
      if !User.authenticate_via_token(params[:email], params[:token])
        head(:unauthorized)
      else
        @user = User.where("email = '#{params[:email]}'").first
      end
    end

    def is_verified
      if !@user.verified
        head(:unauthorized)
      end
    end

end

app/controllers/review_controller.rb
class ReviewController < ActionController::Base
  protect_from_forgery with: :exception
  layout 'application'
  before_action :set_review, only: [:update,:destroy,:edit]
  before_action :is_logged_in, only: [:create]
  before_action :is_mine_or_admin, only: [:destroy,:edit,:update]
  def create
    @location = Location.find(params[:review][:location].to_i)
    @user = User.find(params[:review][:user])
    @review = @location.reviews.build(review_params)
    @user.reviews << @review
    if @review.save
      redirect_to @location, alert: "Successfully Posted Review!"
    else
      redirect_to @location, alert: @review.errors.first
    end
  end
  def edit

  end
  def update
    @location = Location.find(@review.location_id)
    if @review.update_attributes(review_params)
      redirect_to @location, alert: "Successfully Updated Review!"
    else
      redirect_to edit_review_path(@review), alert: @review.errors.first
    end
  end
  def destroy
    @location = Location.find(@review.location_id)
    @review.destroy!
    redirect_to @location, alert: "You have just deleted a review"
  end
  def review_params
    params.require(:review).permit(:message,:score)
  end
  def is_logged_in
    if !signed_in?
      redirect_to location_index_path, alert: "You must be logged in to perform this action."
    elsif !current_user.verified
      redirect_to "/user/disabled_account/#{current_user.id}", alert: "You must verify you email to perform this action."
    end
  end
  def set_review
    @review = Review.find(params[:id])
  end
  def is_mine_or_admin
    if signed_in?
      if current_user.id != Review.find(params[:id]).user_id and current_user.role != "admin"
        redirect_to location_index_path, alert: "You must own or be an admin to access this content."
      elsif !current_user.verified and current_user.role != "admin"
        redirect_to "/user/disabled_account/#{current_user.id}", alert: "You must verify you email to perform this action."
      end
    else
      redirect_to location_index_path, alert: "You must be signed in to access this content."
    end
  end
end

app/views/review/_reviews.html.erb
<div class="container">
  <hr>
  <br>
  <% if signed_in? and current_user.verified and !current_user.has_a_review(location.id) %>
    <h3>Submit A Review</h3>
    <h5>User: <%= current_user.email %></h5>
    <%= form_for(review, url: review_index_path ) do |f| %>
      <div class="form-group">
        <%= f.label :score %>
        <%= f.number_field :score, min: 1, max: 10 %>
      </div>
      <div>
        <%= f.label :message %>
        <%= f.text_area :message, rows: 5 %>
      </div>
      <%= f.hidden_field :location, value: location.id %>
      <%= f.hidden_field :user, value: current_user.id %>
      <br>
      <%= f.submit "Post Review!" %>
    <% end %>
  <% elsif signed_in? and  !user.has_a_review(location.id) %>
    <p>You must verify your email to write a review.</p>
  <% end %>
  <h3>Reviews</h3>
  <% reviews.each do |r, u| %>
    <div class="review-card">
      <div class="review-card-header">
        <%= small_profile_img(u) %><%= u.display %>
        <%= render partial: "sharred/radial_score", locals: {review: true, score: r.score} %>
      </div>
      <div class="review-card-body">
        <p>
          <%= r.message %>
        </p>
        <% if is_mine_or_admin(r.user_id) %>
          <%= link_to("Edit", edit_review_path(r), class: '')  %>
          <%= link_to("Delete", review_path(r), method: :delete, class: '') %>
        <% end %>
        <%= link_to("Report Content", new_report_path({location: nil,photo: nil, review: r.id}), class: '') if signed_in? %>
      </div>
    </div>
  <% end %>
  <% if reviews.length == 0 %>
    <p>There are currently no reviews for this location.</p>
  <% end %>
</div>

app/views/review/edit.html.erb
<div class="container">
  <h1>Edit Your Review</h1>
  <%= form_for(@review, url: review_path(@review) ) do |f| %>
    <div class="form-group">
      <%= f.label :score %>
      <%= f.number_field :score, min: 1, max: 10 %>
    </div>
    <div>
      <%= f.label :message %>
      <%= f.text_area :message, rows: 5 %>
    </div>
    <%= f.hidden_field :location, value: @review.location_id%>
    <%= f.hidden_field :user, value: current_user.id %>
    <br>
    <%= f.submit "Update Review!" %>
  <% end %>
</div>