config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "location#index"
  resources "location"
  resources "review"
  resources "photo"
  resources "report"
  get "admin", to: "admin#index"
  get "/googleb644d22d0a6d8ad2.html", to: "report#googleb644d22d0a6d8ad2"
  get "/landing", to: "user#landing"
  get "/users/all", to: "user#index"
  get "/collection_api", to: "photo#collection_api"
  get "/geo_json_api", to: "location#geo_json_api"
  get "/my_location_api", to: "location#my_location_api"
  get "/user/show/:id", to: "user#show"
  get "/user/enable_account/:id", to: "user#enable_account"
  get "/user/disabled_account/:id", to: "user#disabled_account"
  get "/user/send_email_verification/:id", to: "user#send_email_verification"
  post "/reset_password", to: "user#reset_password"
  get "/new_password/:id", to: "user#new_password"
  post "/change_password/:id", to: "user#change_password"
  delete "/report_destroy/:id", to: "report#report_destroy"
  get "/user/edit_profile/:id", to: "user#edit_profile_image"
  post "/user/update_profile/:id", to: "user#update_profile_image"
  get "/location/admin/merge", to: "location#merge"
  post "/location/admin/merge", to: "location#merge_back_end"
  namespace :api do
    namespace :v1 do
      resources :sessions
      resources :locations
      resources :photos
      resources :users
      resources :reviews
      resources :reports

      post "/sessions/authenticate", to: "sessions#authenticate"
      post "/sessions/create_user", to: "sessions#create_user"
      post "/sessions/edit_user", to: "sessions#edit_user"
      post "/users/password/reset", to: "users#reset_password"

      get "/locations/find/search", to: "locations#search"

    end
  end
end

app/views/admin/index.html.erb
<div class="container">
  <h1>Admin Panel</h1>
  <h3>Some Quick Links</h3>
  <%= link_to "Reported Content", report_index_path %>
  <%= link_to "Merge Locations", "/location/admin/merge" %>
  <h3>Top Users</h3>
  <table class="u-full-width">
    <thead>
      <tr>
        <th>Rank</th>
        <th colspan="2">Email</th>
        <th>Photos</th>
        <th>Views</th>
      <tr>
    </thead>
    <tbody>
      <% i = 0 %>
      <% @top_users.each do |u| %>
        <% i += 1 %>
        <tr>
          <td><%= i.to_s %></td>
          <td colspan="2"><%= link_to u.email, "user/show/"+u.slug %></td>
          <td><%= u.photos.length %></td>
          <td><%= u.cumulative_views %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <h3>Top Photos</h3>
  <%= render partial: "sharred/barchart", locals: {title: "Top Photos Graph", x_label: "Photos", y_label: "Views",values: @top_photos.map { |p| p.views }, labels: @top_photos.map { |p| p.caption}}%>
  <table class="u-full-width">
    <thead>
      <tr>
        <th>Rank</th>
        <th colspan="2">Caption</th>
        <th>User</th>
        <th>Views</th>
      <tr>
    </thead>
    <tbody>
      <% i = 0 %>
      <% @top_photos.each do |p| %>
        <% i += 1 %>
        <tr>
          <td><%= i.to_s %></td>
          <td colspan="2"><%= link_to p.caption, p %></td>
          <td><%= link_to User.find(p.user_id).email, "user/show/"+User.find(p.user_id).slug %></td>
          <td><%= p.views %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>