config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "location#index"
  resources "location"
  resources "review"
  resources "photo"
  resources "report"
  get "admin", to: "admin#index"
  get "/googleb644d22d0a6d8ad2.html", to: "report#googleb644d22d0a6d8ad2"
  get "/landing", to: "user#landing"
  get "/users/all", to: "user#index"
  get "/collection_api", to: "photo#collection_api"
  get "/geo_json_api", to: "location#geo_json_api"
  get "/my_location_api", to: "location#my_location_api"
  get "/user/show/:id", to: "user#show"
  get "/user/enable_account/:id", to: "user#enable_account"
  get "/user/disabled_account/:id", to: "user#disabled_account"
  get "/user/send_email_verification/:id", to: "user#send_email_verification"
  post "/reset_password", to: "user#reset_password"
  get "/new_password/:id", to: "user#new_password"
  post "/change_password/:id", to: "user#change_password"
  delete "/report_destroy/:id", to: "report#report_destroy"
  get "/user/edit_profile/:id", to: "user#edit_profile_image"
  post "/user/update_profile/:id", to: "user#update_profile_image"
  get "/location/admin/merge", to: "location#merge"
  post "/location/admin/merge", to: "location#merge_back_end"
  namespace :api do
    namespace :v1 do
      resources :sessions
      resources :locations
      resources :photos
      resources :users
      resources :reviews
      resources :reports

      post "/sessions/authenticate", to: "sessions#authenticate"
      post "/sessions/create_user", to: "sessions#create_user"
      post "/sessions/edit_user", to: "sessions#edit_user"
      post "/users/password/reset", to: "users#reset_password"

      get "/locations/find/search", to: "locations#search"

    end
  end
end

app/models/report.rb
class Report < ApplicationRecord
  has_many :reviews
  has_many :photos
  has_many :locations
  validate :message_length
  def what_type
    retVal = ""
    if review_id != nil
      retVal = "review"
    elsif photo_id != nil
      retVal = "photo"
    elsif location_id != nil
      retVal = "location"
    end
  end
  def user
    retVal = nil
    if what_type == "review"
      retVal = User.find(Review.find(review_id).user_id)
    elsif what_type == "photo"
      retVal = User.find(Photo.find(photo_id).user_id)
    elsif what_type == "location"
      retVal = User.find(Location.find(location_id).user_id)
    end
  end
  def link
    retVal = nil
    if what_type == "review"
      retVal = Location.find(Review.find(review_id).location_id)
    elsif what_type == "photo"
      retVal = Photo.find(photo_id)
    elsif what_type == "location"
      retVal = Location.find(location_id)
    end
  end
  def message_length
    if message.length < 6
      errors.add(:message,"Your message must be atleast six characters long.")
    end
  end
end

app/controllers/api/v1/reports_controller.rb
class Api::V1::ReportsController < ApiController
  before_action :is_authencticated, only: [:create]

  def create
    @report = Report.create(report_params)
    if @report.save
      UserMailer.new_report(@report.id,@user.id).deliver!
      render json: { report: @report }
    else
      render json: { errors: @report.errors }
    end
  end

  private

    def report_params
      params.permit(:message, :location_id, :review_id, :photo_id)
    end

    def is_authencticated
      @user = nil
      if !User.authenticate_via_token(params[:email], params[:token])
        head(:unauthorized)
      else
        @user = User.where("email = '#{params[:email]}'").first
      end
    end

end

app/controllers/report_controller.rb
class ReportController < ActionController::Base
  protect_from_forgery with: :exception
  layout 'application'
  before_action :remove_old_reports, only: [:index,:show]
  before_action :is_admin, only: [:index,:show,:destroy]
  before_action :is_logged_in, only: [:new,:create]
  before_action :set_report, only: [:show,:destroy,:report_destroy]
  def index
    @reports = Report.all
  end
  def show
    @report = Report.find(params[:id])
  end
  def new
    @report = Report.new
    @review = params[:review]
    @location = params[:location]
    @photo = params[:photo]
  end
  def googleb644d22d0a6d8ad2
    render :layout => false
  end
  def create
    @report = Report.create(report_params)
    if @report.save
      UserMailer.new_report(@report.id,current_user.id).deliver!
      redirect_to location_index_path, alert: "Successfully reported content."
    else
      redirect_to new_report_path, alert: @report.errors.first
    end
  end
  def destroy
    @report.destroy!
    redirect_to report_index_path, alert: "Report Resolved."
  end
  def report_destroy
    if @report.what_type == "review"
      Review.find(@report.review_id).destroy!
    elsif @report.what_type == "location"
      Location.find(@report.location_id).destroy!
    elsif @report.what_type == "photo"
      Photo.find(@report.photo_id).destroy!
    end
    @report.destroy!
    redirect_to report_index_path, alert: "Deleted item and resolved report."
  end
  def report_params
    params.require(:report).permit(:message, :user_id, :location_id, :review_id, :photo_id)
  end
  def set_report
    @report = Report.find(params[:id])
  end
  def is_logged_in
    if signed_in?
      if !current_user.verified
        redirect_to location_index_path, alert: "You must verify your account to report content."
      end
    else
      redirect_to location_index_path, alert: "You must be signed in to report content."
    end
  end
  def is_admin
    if signed_in?
      if current_user.role != "admin"
        redirect_to location_index_path, alert: "You must be an admin to access this content."
      end
    else
      redirect_to location_index_path, alert: "You must be an admin to access this content."
    end
  end
  def remove_old_reports
    Report.all.each do |r|
      if r.what_type == "location"
        r.destroy if Location.where("id=#{r.location_id}").length == 0
      elsif r.what_type == "review"
        r.destroy if Review.where("id=#{r.review_id}").length == 0
      elsif r.what_type == "photo"
        r.destroy if Photo.where("id=#{r.photo_id}").length == 0
      end
    end
  end
end

app/views/report/index.html.erb
<div class="container">
  <h1>Reported Content</h1>
  <table class="u-full-width">
    <thead>
      <tr>
        <th colspan="3">Message</th>
        <th>Type</th>
        <th>User</th>
        <th>Link</th>
        <th>Resolve</th>
      </tr>
    </thead>
    <tbody>
      <% @reports.each do |r| %>
        <tr>
          <td colspan="3"><%= r.message %></td>
          <td><%= r.what_type %></td>
          <td><%= link_to(r.user.email, "/user/show/"+r.user.slug) if r.user != nil %></td>
          <td><%= link_to "View", r.link %></td>
          <td><%= link_to "Resolve", r %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/report/new.html.erb
<div class="container">
  <h1>Report Content</h1>
  <p>Reported content will be investigated by a site administrator before any action will be taken. Content that violates our terms of service will be edited or taken down. A account may be terminated after repeat violations or extreme acts.</p>
  <%= form_for(@report, url: report_index_path) do |f| %>
    <div class="form-group">
      <%= f.label :message %>
      <%= f.text_area :message, width:"100%", rows: "5" %>
    </div>
    <%= f.hidden_field :review_id, value: @review %>
    <%= f.hidden_field :location_id, value: @location %>
    <%= f.hidden_field :photo_id, value: @photo %>
    <%= f.submit "Submit Report", class: 'button' %>
  <% end %>
</div>

app/views/report/show.html.erb
<div class="container">
  <h1>Resolve Reported Content</h1>
  <hr>
  <p>User: <%= link_to(@report.user.email, "/user/show/#{@report.user.slug}") if @report.user != nil %></p>
  <%= link_to "View all Reported Content", report_index_path, class: 'button' %>
  <%= link_to "View", @report.link, class: 'button' %>
  <% if @report.what_type == "location" %>
    <%= link_to "Edit", edit_location_path(@report.location_id), class: "button" %>
  <% elsif @report.what_type == "photo" %>
    <%= link_to "Edit", edit_photo_path(@report.photo_id), class: "button" %>
  <% elsif @report.what_type == "review" %>
    <%= link_to "Edit", edit_review_path(@report.review_id), class: "button" %>
  <% end %>
  <%= link_to "Delete", "/report_destroy/#{@report.id}", class: "button", method: :delete %>
  <%= link_to "Mark as Resolved", report_path(@report.id), class: 'button', method: :delete %>
  <p>Message: <%= @report.message %></p>
</div>