config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "location#index"
  resources "location"
  resources "review"
  resources "photo"
  resources "report"
  get "admin", to: "admin#index"
  get "/googleb644d22d0a6d8ad2.html", to: "report#googleb644d22d0a6d8ad2"
  get "/landing", to: "user#landing"
  get "/users/all", to: "user#index"
  get "/collection_api", to: "photo#collection_api"
  get "/geo_json_api", to: "location#geo_json_api"
  get "/my_location_api", to: "location#my_location_api"
  get "/user/show/:id", to: "user#show"
  get "/user/enable_account/:id", to: "user#enable_account"
  get "/user/disabled_account/:id", to: "user#disabled_account"
  get "/user/send_email_verification/:id", to: "user#send_email_verification"
  post "/reset_password", to: "user#reset_password"
  get "/new_password/:id", to: "user#new_password"
  post "/change_password/:id", to: "user#change_password"
  delete "/report_destroy/:id", to: "report#report_destroy"
  get "/user/edit_profile/:id", to: "user#edit_profile_image"
  post "/user/update_profile/:id", to: "user#update_profile_image"
  get "/location/admin/merge", to: "location#merge"
  post "/location/admin/merge", to: "location#merge_back_end"
  namespace :api do
    namespace :v1 do
      resources :sessions
      resources :locations
      resources :photos
      resources :users
      resources :reviews
      resources :reports

      post "/sessions/authenticate", to: "sessions#authenticate"
      post "/sessions/create_user", to: "sessions#create_user"
      post "/sessions/edit_user", to: "sessions#edit_user"
      post "/users/password/reset", to: "users#reset_password"

      get "/locations/find/search", to: "locations#search"

    end
  end
end

app/models/location.rb
class Location < ApplicationRecord
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged
  geocoded_by :full_address do |object, results|
    if results.present?
     object.latitude = results.first.latitude
     object.longitude = results.first.longitude
    else
     object.latitude = nil
     object.longitude = nil
    end
  end
  validate :address, :city, :state, :country, :title, :location_validate, :found_address_presence
  before_validation :geocode
  has_many :reviews, dependent: :destroy
  has_many :photos, dependent: :destroy
  belongs_to :user
  def full_address
    addressArray = [address, city, state, country]
    addressArray.compact.join(", ")
  end

  def slug_candidates
    [
      :title,
      [:title, :city],
      [:title, :address, :city],
      [:title, :address, :city, :state]
    ]
  end

  def average_score
    avg_score = 0
    reviews.each do |r|
      avg_score += r.score
    end
    if reviews.length != 0
      return avg_score.to_f/reviews.length.to_f
    else
      return 0
    end
  end
  def location_validate
    if title != ""
      if address != ""
        if city != ""
          if state != ""
            if country != ""

            else
              errors.add(:country,"Country may not be blank.")
            end
          else
            errors.add(:state,"State may not be blank.")
          end
        else
          errors.add(:city,"City may not be blank.")
        end
      else
        errors.add(:country,"Address may not be blank.")
      end
    else
      errors.add(:title,"Title may not be blank.")
    end
  end
  def found_address_presence
    if latitude.blank? || longitude.blank?
      errors.add(:address, "We couldn't find the address.")
    end
  end
end

app/controllers/api/v1/locations_controller.rb
class Api::V1::LocationsController < ApiController
  before_action :is_authencticated, only: [:create, :update]
  before_action :is_verified, only: [:create, :update]
  before_action :set_location, only: [:show, :update]
  before_action :is_mine, only: [:update]

  def index
    @locations = Location.all
    render json: @locations
  end

  def show
    return_location_show @location
  end

  def create
    @location = @user.locations.create(location_params)
    if @location.save
      return_location_show @location
    else
      render json: { errors: @location.errors }
    end
  end

  def update
    if @location.update_attributes(location_params)
      return_location_show @location
    else
      render json: { errors: @location.errors }
    end
  end

  def search
    query = params[:query].downcase
    @locations = Location.where("LOWER(title) LIKE '%#{query}%' OR LOWER(address) LIKE '%#{query}%' OR LOWER(city) LIKE '%#{query}%' OR LOWER(state) LIKE '%#{query}%' OR LOWER(country) LIKE '%#{query}%'")
    render json: @locations
  end

  private

    def location_params
      params.permit(:title,:city,:address,:state,:country,:id)
    end

    def is_authencticated
      @user = nil
      if !User.authenticate_via_token(params[:email], params[:token])
        head(:unauthorized)
      else
        @user = User.where("email = '#{params[:email]}'").first
      end
    end

    def is_verified
      if !@user.verified
        head(:unauthorized)
      end
    end

    def return_location_show location
      ph = location.photos.mostViews
      users = User.joins(:photos).where("photos.location_id = #{location.id}").order("photos.views DESC")
      photos = ph.zip(users).map do |p, u|
        { id: p.id, zoom: p.zoom, offsetX: p.offsetX, offsetY: p.offsetY, width: p.width, height: p.height, caption: p.caption, user_id: p.user_id, img_url: p.img_url.url, views: p.views, user_display: u.display, user_profile: u.profile_img.url, user_zoom: u.zoom, user_width: u.width, user_height: u.height, user_offsetX: u.offsetX, user_offsetY: u.offsetY}
      end
      rv_users = User.find_by_sql("SELECT u.* FROM users u JOIN reviews r ON r.user_id = u.id WHERE r.location_id = #{location.id} ORDER BY r.score DESC")
      rv = Review.find_by_sql("SELECT r.* FROM reviews r JOIN users u ON r.user_id = u.id WHERE r.location_id = #{location.id} ORDER BY r.score DESC")
      reviews = rv.zip(rv_users).map do |r, u|
        { id: r.id, score: r.score, message: r.message ,user_id: r.user_id, user_display: u.display, user_profile: u.profile_img.url, user_zoom: u.zoom, user_width: u.width, user_height: u.height, user_offsetX: u.offsetX, user_offsetY: u.offsetY}
      end
      render json:  { location: location, photos: photos, reviews: reviews }
    end

    def is_mine
      if @user.id.to_i != @location.user_id.to_i
        head(:unauthorized)
      end
    end

    def set_location
      @location = Location.find(params[:id])
    end
end

app/controllers/location_controller.rb
class LocationController < ActionController::Base
  protect_from_forgery with: :exception
  layout 'application'
  before_action :set_location, only: [:show,:edit,:update,:destroy]
  before_action :send_initial_email_verification_email, only: [:index,:show,:edit,:destroy,:update,:new]
  before_action :is_mine_or_admin, only: [:edit,:update,:destroy]
  before_action :is_admin, only: [:merge]
  before_action :is_logged_in, only: [:new,:create]
  before_action :send_to_landing, only: [:index]
  def index
    
  end
  def show
    reviews = Review.find_by_sql("SELECT r.*  FROM reviews r JOIN users u ON r.user_id = u.id WHERE r.location_id=#{@location.id} ORDER BY r.id DESC")
    users = User.find_by_sql("SELECT u.*  FROM users u JOIN reviews r ON r.user_id = u.id WHERE r.location_id=#{@location.id} ORDER BY r.id DESC")
    @reviews = reviews.zip(users)
    @review = Review.new
    @friendly_address = ""
    @location.address.split(" ").each do |m|
      @friendly_address += m + "+"
    end
    @location.city.split(" ").each do |m|
      @friendly_address += m + "+"
    end
    @location.state.split(" ").each do |m|
      @friendly_address += m + "+"
    end
    @location.country.split(" ").each do |m|
      @friendly_address += m + "+"
    end
  end
  def edit

  end
  def destroy
    @location.destroy!
    redirect_to location_index_path
  end

  def update
    if @location.update_attributes(location_params)
      redirect_to location_path
    else
      redirect_to edit_location_path(@location), alert: @location.errors.first
    end
  end
  def create
    @user = User.find(params[:location][:user].to_i)
    @location = @user.locations.create(location_params)
    if @user.save
      redirect_to location_path(@location)
    else
      redirect_to new_location_path, alert: @location.errors.first
    end
  end
  def new
    @location = Location.new
  end
  def location_params
    params.require(:location).permit(:title,:city,:address,:state,:country,:id,:locationOne,:locationTwo)
  end
  def my_location_api
    location = JSON.parse(open("http://ip-api.com/json").read)
    @my_location = { latitude: location["lat"], longitude: location["lon"]}
    render json: @my_location
  end
  def geo_json_api
    @locations = Location.all
    @geo_json = []
    @locations.each do |l|
      img_url = ""
      offSetX = nil
      offSetY = nil
      zoom = nil
      width = nil
      height = nil
      if l.photos.length > 0
        photo = l.photos.mostViews.first
        img_url = photo.img_url.url
        offsetX = photo.offsetX
        offsetY = photo.offsetY
        zoom = photo.zoom
        width = photo.width
        height = photo.height
      end
      temp = { title: l.title , id: l.id, url: location_path(l), average_score: l.average_score, img_url: img_url , address: l.full_address, coordinates: [l.latitude,l.longitude], slug: l.slug, offsetX: offsetX, offsetY: offsetY, zoom: zoom, width: width, height: height}
      @geo_json.push temp
    end
    render json: @geo_json
  end
  def merge 
    @locations = Location.all
  end
  def merge_back_end
      puts params 
      if params[:location_one][:location_one] != "" && params[:location_two][:location_two] != ""
        location_one = Location.find(params[:location_one][:location_one])
        location_two = Location.find(params[:location_two][:location_two])
        if location_one && location_two
          photos = location_two.photos 
          reviews = location_two.reviews
          reports = Report.where("location_id="+location_two.id.to_s) 
          photos.each do |p|
            p.update_attribute("location_id", location_one.id)
          end
          reviews.each do |r|
            r.update_attribute("location_id", location_one.id)
          end
          reports.each do |r|
            r.update_attribute("location_id", location_one.id)
          end
          location_two.destroy!
          redirect_to location_path(location_one, alert: "Successfully merged locations")
        else 
          redirect_to "/location/admin/merge", alert: "You must select two valid locations"
        end
      else 
        redirect_to "/location/admin/merge", alert: "You must select two valid locations" 
      end
  end
  def set_location
    @location = Location.where("slug = '#{params[:id]}'").first
  end
  def send_initial_email_verification_email
    if signed_in?
      if current_user.token == nil
        @user = User.find(current_user.id)
        if @user.profile_img?
          @user.update_attribute("width",@user.profile_img.width)
          @user.update_attribute("height",@user.profile_img.height)
        end
        @user.update_attribute("token",rand(36**16).to_s(36))
        @user = @user.id
        UserMailer.verify_email(@user).deliver!
        redirect_to location_index_path, alert: "Check your email for an email that will verify your email address and enable your accounts."
      end
    end
  end
  def is_logged_in
    if !signed_in?
      redirect_to location_index_path, alert: "You must be logged in to perform this action."
    elsif !current_user.verified
      redirect_to "/user/disabled_account/#{current_user.id}", alert: "You must verify your email to perform this action."
    end
  end
  def is_mine_or_admin
    if signed_in?
      if @location.user_id.to_i != current_user.id.to_i and current_user.role != "admin"
        redirect_to location_index_path, alert: "You must own or be an admin to access this content."
      elsif !current_user.verified
        redirect_to "/user/disabled_account/#{current_user.id}", alert: "You must verify you email to perform this action."
      end
    else
      redirect_to location_index_path, alert: "You must be signed in to access this content."
    end
  end
  def send_to_landing
    if !signed_in? and params[:see] != "true"
      redirect_to "/landing"
    end
  end
  def is_admin 
    if signed_in?
      if current_user.role != "admin"
        redirect_to location_index_path, alert: "You must be an admin to access this page."
      end
    else
      redirect_to location_index_path, alert: "You must be an admin to access this page."
    end
  end
end

app/views/location/_form.html.erb
<%= form_for(location ,url: path ) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div class="form-group">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
  <div class="form-group">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>
  <%= f.hidden_field :user, value: current_user.id  %>
  <%= f.submit %>
<% end %>

app/views/location/edit.html.erb
<div class="container">
  <h1>Edit Location</h1>
  <%= render partial: "form", locals: {location: @location, path: location_path(@location)} %>
</div>

app/views/location/index.html.erb
<!-- This is to show the appropiate content for the particular user !-->
<% class2 = '' %>
<div class="map-container">
  <% if signed_in? and current_user.verified %>
    <%= link_to "Create Location", new_location_path, class: "button create-button" %>
  <% elsif signed_in? %>
    <div class="map-alert">
      <% class2 = 'not-verified' if !current_user.verified %>
      <p>You must verify your email in order to create a location.</p>
      <a href="<%= root_url %>user/disabled_account/<%= current_user.slug %>">Enable Your Account.</a>
    </div>
  <% end %>
  <%= javascript_pack_tag 'application' %>
  <%= react_component("LocationSearch",{ rootUrl: !Rails.env.production? ? root_url :  'https://geofoc.us/' }) %>
  <!-- This is for the Mapbox JS API !-->
  <script type="text/javascript" charset="utf-8">var ROOT_URL = '<%= !Rails.env.production? ? root_url :  'https://geofoc.us/'%>';</script>
  <script src='https://api.mapbox.com/mapbox-gl-js/v0.44.0/mapbox-gl.js'></script>
  <link href='https://api.mapbox.com/mapbox-gl-js/v0.44.0/mapbox-gl.css' rel='stylesheet' />
  <div id='map' ></div>
</div>
<style>
  .nav{
    position: relative !important;
    width: inherit !important;,
    margin-bottom: 20px;
  }

  #map{
    margin-top: 20px !important;
  }

  html, body{
    padding: 0 !important;
  }
</style>

app/views/location/merge.html.erb
<div class="container">
    <h1>Select Locations to merge</h1>
    <%= form_tag(url: "/location/admin/merge", method: "post") do |f|%>
        <label for="locationOne">Location One</label>
        <%= select("location_one", "location_one", @locations.all.collect {|l| [ l.title+" - "+l.id.to_s+" - "+l.address, l.id ] }, { include_blank: true }) %>
        <label for="locationTwo">Location Two</label>
        <%= select("location_two", "location_two", @locations.all.collect {|l| [ l.title+" - "+l.id.to_s+" - "+l.address, l.id ] }, { include_blank: true }) %>
        <br />
        <input type="submit" value="Merge Locations" style="margin-top: 20px;">
    <% end %>
</div>

app/views/location/new.html.erb
<div class="container">
  <h1>Create New Location</h1>
  <%= render partial: "form", locals: {location: @location, path: location_index_path} %>
</div>

app/views/location/show.html.erb
<%= javascript_pack_tag 'application' %>
<div class="location-header" style="background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url(<%= @location.photos.mostViews[0].img_url.url if @location.photos.length != 0%><%= 'https://cdn.theatlantic.com/assets/media/img/mt/2016/03/RTX283V4/lead_960.jpg?1457553386' if @location.photos.length == 0 %>);">
  <h1><%= @location.title %></h1>
</div>
<div class="container">
  <div class="row">
    <p><%= @location.address + ", " + @location.city + ", " + @location.state + ", " + @location.country %></p>
    <!--
    <div class="review-score white-review-background" style="<%= 'display: none;' if @location.average_score == 0 %>">
      <div class="review-score-value" style="width:<%= @location.average_score*10  if @location.average_score != 0 %><%= '0'  if @location.average_score == 0 %>%;<%= 'display:none;' if @location.average_score == 0 %>">
      </div>
      <p><%= @location.average_score %>/10</p>
    </div>
    -->
    <% if @location.average_score != 0 %>
      <div class="location-radial-score-wrapper">
        <%= render partial: "sharred/radial_score", locals: {review: false, score: @location.average_score} %>
        <h1>Average Review</h1>
      </div>
    <% end %>
    <br />
    <% if signed_in? %>
      <% if is_mine_or_admin(@location.user_id.to_i)%>
        <%= link_to "Edit", edit_location_path(@location), class: "button" %>
        <%= link_to "Delete", location_path(@location), method: :delete, class: "button" %>
      <% elsif !current_user.verified %>
        <p>You must verify your email to add photos.</p>
      <% end %>
      <% if current_user.verified %>
        <%= link_to("Add Photo", new_photo_path + "/?location=#{@location.id}&user=#{current_user.id}", class: "button") %>
        <%= link_to "Report Content", new_report_path({location: @location.id,photo: nil, review: nil}), class: 'button' %>
      <% end %>
    <% end %>
  </div>
  <!-- <%= render partial: "photo/collection", locals: {collection: @location.photos, title: "Photos", collumns: 3, limit: nil, location: @location.id, user: nil} %> -->
  <%= react_component("Collection",{ title: "Photos", location: @location.id.to_s, user: "", rootUrl: !Rails.env.production? ? root_url :  'https://geofoc.us/', currentUser: current_user, collumns: 3, search: true  }) %>
</div>
<%= render partial: "review/reviews", locals: {review: @review, reviews: @reviews, location: @location, user: current_user ? User.find(current_user.id) : {}} %>
<%= render partial: "sharred/scroll_to_top" %>